### PR TITLE
Add circleci config file

### PR DESCRIPTION
**Pull request by gianarb**
Enable ci using circleci

Signed-off-by: Gianluca Arbezzano <gianarb92@gmail.com>

### CODE REVIEW

**Comment by MeneDev** [comment]
I think you need to use the step [`setup_remote_docker`]( https://circleci.com/docs/2.0/building-docker-images/).

If you need some inspiration you can look at: https://github.com/MeneDev/dockmoor
I've split it into two parts: one for creating a builder, containing dependencies that are not part of `Gopkg.*` (e.g. `dep`) in an own Docker Image (in the `.builder` folder) and the rest is in CircleCI. The Image is also build in CircleCI when the Dockerfile changes.

However, I'm not yet using `setup_remote_docker`

**Comment by rnorth** [comment]
I've enabled CircleCI for you, so hopefully this should now work.

**Comment by gianarb** [comment]
I think I managed to reproduce the failure we have in CIRCLE, do you have an idea @mraerino ?
```
docker run -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:/hello -it -w /hello --rm golang:1.11 go test ./...
```

**Comment by gianarb** [comment]
After the above commit the docker in docker example works.

```
docker run -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:/hello -it -w /hello --rm golang:1.11 go test ./...
```

but circleci still complains

**Comment by mraerino** [comment]
I see. That means we need to make that more flexible based on whatever the `DaemonHost()` method of the docket client gives us.
Ryuk should accept a `DOCKER_HOST` for this.

**Comment by gianarb** [comment]
I have fixed a couple of dependency issue today #39 but we are still blocked:

```
$ docker run -v /var/run/docker.sock:/var/run/docker.sock --rm -u root -v $PWD:/p -w /p circleci/golang:1.11 go test ./...

--- FAIL: TestTwoContainersExposingTheSamePort (11.90s)
    docker_test.go:26: failed to create container: connecting to reaper failed: Connecting to Ryuk on 172.17.0.1:32768 failed: dial tcp 172.17.0.1:32768: i/o timeout
--- FAIL: TestContainerCreation (10.41s)
    docker_test.go:92: failed to create container: connecting to reaper failed: Connecting to Ryuk on 172.17.0.1:32769 failed: dial tcp 172.17.0.1:32769: i/o timeout
--- FAIL: TestLegacyTwoContainersExposingTheSamePort (10.40s)
    legacy_test.go:22: failed to launch generic container: failed to create container: connecting to reaper failed: Connecting to Ryuk on 172.17.0.1:32770 failed: dial tcp 172.17.0.1:32770: i/o timeout
--- FAIL: TestLegacyContainerCreation (10.45s)
    legacy_test.go:73: failed to launch generic container: failed to create container: connecting to reaper failed: Connecting to Ryuk on 172.17.0.1:32771 failed: dial tcp 172.17.0.1:32771: i/o timeout
--- FAIL: TestLegacyContainerRespondsWithHttp200ForIndex (10.40s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7b388e]

goroutine 114 [running]:
testing.tRunner.func1(0xc00032c900)
	/usr/local/go/src/testing/testing.go:792 +0x387
panic(0x828960, 0xbdc790)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/testcontainers/testcontainer-go.TestLegacyContainerRespondsWithHttp200ForIndex(0xc00032c900)
	/go/src/github.com/testcontainers/testcontainer-go/legacy_test.go:145 +0x1ae
testing.tRunner(0xc00032c900, 0x8b8610)
	/usr/local/go/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:878 +0x35c
FAIL	github.com/testcontainers/testcontainer-go	53.571s
?   	github.com/testcontainers/testcontainer-go/wait	[no test files]
Exited with code 1
```
I  will keep trying!

**Comment by gianarb** [comment]
CircleCi and travis uses the same setup. There is not really a benefit about having both of them running. For now we will keep only travis

**Pull request closed without merging**
